// src/constants/partido.ts

import { Partido } from '../types/Partido';

export const partidoEjemploFinalizado: Partido = {
  id: 'partido123',
  jornadaId: 'jornada7',
  estado: 'finalizado',
  fecha: new Date('2025-05-15T19:00:00'),
  cancha: 'Pabellón Central Las Palmas',
  tipoCompeticion: 'liga-regular',
  equipoLocal: {
    id: '92a2d70d-199b-4b40-8694-2636cd7a9429',
    nombre: 'Minesota Caballo y Rey',
    escudoUrl:
      'https://firebasestorage.googleapis.com/v0/b/glmba-tfg.firebasestorage.app/o/escudos_equipos%2F6f1d09cb-8231-4717-a4df-a633cc3ee205.jpg?alt=media&token=5d7af86c-7984-4d27-b8a0-f55fcfb7eda3',
  },
  equipoVisitante: {
    id: 'aa0e3551-af79-4ac8-a5bb-47bf400ff695',
    nombre: 'Zona Norte',
    escudoUrl:
      'https://firebasestorage.googleapis.com/v0/b/glmba-tfg.firebasestorage.app/o/escudos_equipos%2Fc36c1865-6c70-4560-a52e-86a213e09ce5.jpg?alt=media&token=334684e8-df0b-4871-97f2-42c243e28653',
  },
  resultado: {
    puntosLocal: 71,
    puntosVisitante: 66,
  },
  estadisticasJugadores: {
    local: {
      jugador1: {
        nombre: 'Jugador 1',
        apellidos: 'Apellido 1',
        fotoUrl: 'https://example.com/fotos/jugador1.jpg',
        puntos: 15,
        tirosLibres: { anotados: 3, fallados: 1 },
        tirosDos: { anotados: 4, fallados: 3 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 4,
        rebotes: 6,
        faltasCometidas: 1,
      },
      jugador2: {
        nombre: 'Jugador 2',
        apellidos: 'Apellido 2',
        fotoUrl: 'https://example.com/fotos/jugador2.jpg',
        puntos: 12,
        tirosLibres: { anotados: 2, fallados: 0 },
        tirosDos: { anotados: 3, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 3,
        rebotes: 4,
        faltasCometidas: 2,
      },
      jugador3: {
        nombre: 'Jugador 3',
        apellidos: 'Apellido 3',
        fotoUrl: 'https://example.com/fotos/jugador3.jpg',
        puntos: 10,
        tirosLibres: { anotados: 1, fallados: 0 },
        tirosDos: { anotados: 3, fallados: 1 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 2,
        rebotes: 5,
        faltasCometidas: 1,
      },
      jugador4: {
        nombre: 'Jugador 4',
        apellidos: 'Apellido 4',
        fotoUrl: 'https://example.com/fotos/jugador4.jpg',
        puntos: 18,
        tirosLibres: { anotados: 4, fallados: 1 },
        tirosDos: { anotados: 5, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 1,
        rebotes: 3,
        faltasCometidas: 2,
      },
      jugador5: {
        nombre: 'Jugador 5',
        apellidos: 'Apellido 5',
        fotoUrl: 'https://example.com/fotos/jugador5.jpg',
        puntos: 16,
        tirosLibres: { anotados: 2, fallados: 1 },
        tirosDos: { anotados: 4, fallados: 2 },
        tirosTres: { anotados: 2, fallados: 3 },
        asistencias: 2,
        rebotes: 6,
        faltasCometidas: 1,
      },
    },
    visitante: {
      jugador6: {
        nombre: 'Jugador 6',
        apellidos: 'Apellido 6',
        fotoUrl: 'https://example.com/fotos/jugador6.jpg',
        puntos: 14,
        tirosLibres: { anotados: 2, fallados: 2 },
        tirosDos: { anotados: 4, fallados: 3 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 2,
        rebotes: 5,
        faltasCometidas: 2,
      },
      jugador7: {
        nombre: 'Jugador 7',
        apellidos: 'Apellido 7',
        fotoUrl: 'https://example.com/fotos/jugador7.jpg',
        puntos: 13,
        tirosLibres: { anotados: 1, fallados: 0 },
        tirosDos: { anotados: 4, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 3,
        rebotes: 3,
        faltasCometidas: 1,
      },
      jugador8: {
        nombre: 'Jugador 8',
        apellidos: 'Apellido 8',
        fotoUrl: 'https://example.com/fotos/jugador8.jpg',
        puntos: 12,
        tirosLibres: { anotados: 3, fallados: 1 },
        tirosDos: { anotados: 3, fallados: 1 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 1,
        rebotes: 4,
        faltasCometidas: 2,
      },
      jugador9: {
        nombre: 'Jugador 9',
        apellidos: 'Apellido 9',
        fotoUrl: 'https://example.com/fotos/jugador9.jpg',
        puntos: 15,
        tirosLibres: { anotados: 4, fallados: 0 },
        tirosDos: { anotados: 4, fallados: 3 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 2,
        rebotes: 4,
        faltasCometidas: 1,
      },
      jugador10: {
        nombre: 'Jugador 10',
        apellidos: 'Apellido 10',
        fotoUrl: 'https://example.com/fotos/jugador10.jpg',
        puntos: 12,
        tirosLibres: { anotados: 2, fallados: 1 },
        tirosDos: { anotados: 3, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 2,
        rebotes: 3,
        faltasCometidas: 1,
      },
    },
  },

  estadisticasEquipos: {
    porCuarto: {
      Q1: {
        local: {
          puntos: 18,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 5, fallados: 2 },
          tirosTres: { anotados: 1, fallados: 2 },
          asistencias: 3,
          rebotes: 6,
          faltasCometidas: 2,
        },
        visitante: {
          puntos: 15,
          tirosLibres: { anotados: 2, fallados: 1 },
          tirosDos: { anotados: 4, fallados: 2 },
          tirosTres: { anotados: 1, fallados: 1 },
          asistencias: 2,
          rebotes: 5,
          faltasCometidas: 1,
        },
      },
      Q2: {
        local: {
          puntos: 15,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 4, fallados: 3 },
          tirosTres: { anotados: 1, fallados: 1 },
          asistencias: 2,
          rebotes: 5,
          faltasCometidas: 1,
        },
        visitante: {
          puntos: 16,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 5, fallados: 2 },
          tirosTres: { anotados: 1, fallados: 2 },
          asistencias: 3,
          rebotes: 5,
          faltasCometidas: 1,
        },
      },
      Q3: {
        local: {
          puntos: 20,
          tirosLibres: { anotados: 4, fallados: 1 },
          tirosDos: { anotados: 6, fallados: 2 },
          tirosTres: { anotados: 2, fallados: 1 },
          asistencias: 4,
          rebotes: 7,
          faltasCometidas: 2,
        },
        visitante: {
          puntos: 17,
          tirosLibres: { anotados: 4, fallados: 1 },
          tirosDos: { anotados: 5, fallados: 3 },
          tirosTres: { anotados: 1, fallados: 1 },
          asistencias: 3,
          rebotes: 5,
          faltasCometidas: 2,
        },
      },
      Q4: {
        local: {
          puntos: 18,
          tirosLibres: { anotados: 2, fallados: 0 },
          tirosDos: { anotados: 4, fallados: 3 },
          tirosTres: { anotados: 2, fallados: 2 },
          asistencias: 3,
          rebotes: 6,
          faltasCometidas: 2,
        },
        visitante: {
          puntos: 18,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 4, fallados: 4 },
          tirosTres: { anotados: 2, fallados: 1 },
          asistencias: 2,
          rebotes: 4,
          faltasCometidas: 3,
        },
      },
    },
    totales: {
      local: {
        puntos: 71,
        tirosLibres: { anotados: 12, fallados: 3 },
        tirosDos: { anotados: 19, fallados: 10 },
        tirosTres: { anotados: 6, fallados: 6 },
        asistencias: 12,
        rebotes: 24,
        faltasCometidas: 7,
      },
      visitante: {
        puntos: 66,
        tirosLibres: { anotados: 12, fallados: 4 },
        tirosDos: { anotados: 18, fallados: 11 },
        tirosTres: { anotados: 5, fallados: 5 },
        asistencias: 10,
        rebotes: 19,
        faltasCometidas: 7,
      },
    },
  },
};
