// src/constants/partido.ts

import { Partido } from '../types/Partido';

export const partidoEjemploFinalizado: Partido = {
  id: 'partido123',
  jornadaId: 'jornada7',
  estado: 'finalizado',
  fecha: new Date('2025-05-15T19:00:00'),
  cancha: 'Pabellón Central Las Palmas',
  equipoLocal: {
    id: '92a2d70d-199b-4b40-8694-2636cd7a9429',
    nombre: 'Minesota Caballo y Rey',
    escudoUrl:
      'https://firebasestorage.googleapis.com/v0/b/glmba-tfg.firebasestorage.app/o/escudos_equipos%2F6f1d09cb-8231-4717-a4df-a633cc3ee205.jpg?alt=media&token=5d7af86c-7984-4d27-b8a0-f55fcfb7eda3',
  },
  equipoVisitante: {
    id: 'aa0e3551-af79-4ac8-a5bb-47bf400ff695',
    nombre: 'Zona Norte',
    escudoUrl:
      'https://firebasestorage.googleapis.com/v0/b/glmba-tfg.firebasestorage.app/o/escudos_equipos%2Fc36c1865-6c70-4560-a52e-86a213e09ce5.jpg?alt=media&token=334684e8-df0b-4871-97f2-42c243e28653',
  },
  resultado: {
    puntosLocal: 71,
    puntosVisitante: 66,
  },
  estadisticasJugadores: {
    local: {
      jugador1: {
        puntos: 15,
        tirosLibres: { anotados: 3, fallados: 1 },
        tirosDos: { anotados: 4, fallados: 3 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 4,
        rebotes: 6,
        faltasCometidas: 1,
      },
      jugador2: {
        puntos: 12,
        tirosLibres: { anotados: 2, fallados: 0 },
        tirosDos: { anotados: 3, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 3,
        rebotes: 4,
        faltasCometidas: 2,
      },
      jugador3: {
        puntos: 10,
        tirosLibres: { anotados: 1, fallados: 0 },
        tirosDos: { anotados: 3, fallados: 1 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 2,
        rebotes: 5,
        faltasCometidas: 1,
      },
      jugador4: {
        puntos: 18,
        tirosLibres: { anotados: 4, fallados: 1 },
        tirosDos: { anotados: 5, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 1,
        rebotes: 3,
        faltasCometidas: 2,
      },
      jugador5: {
        puntos: 16,
        tirosLibres: { anotados: 2, fallados: 1 },
        tirosDos: { anotados: 4, fallados: 2 },
        tirosTres: { anotados: 2, fallados: 3 },
        asistencias: 2,
        rebotes: 6,
        faltasCometidas: 1,
      },
    },
    visitante: {
      jugador6: {
        puntos: 14,
        tirosLibres: { anotados: 2, fallados: 2 },
        tirosDos: { anotados: 4, fallados: 3 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 2,
        rebotes: 5,
        faltasCometidas: 2,
      },
      jugador7: {
        puntos: 13,
        tirosLibres: { anotados: 1, fallados: 0 },
        tirosDos: { anotados: 4, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 3,
        rebotes: 3,
        faltasCometidas: 1,
      },
      jugador8: {
        puntos: 12,
        tirosLibres: { anotados: 3, fallados: 1 },
        tirosDos: { anotados: 3, fallados: 1 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 1,
        rebotes: 4,
        faltasCometidas: 2,
      },
      jugador9: {
        puntos: 15,
        tirosLibres: { anotados: 4, fallados: 0 },
        tirosDos: { anotados: 4, fallados: 3 },
        tirosTres: { anotados: 1, fallados: 1 },
        asistencias: 2,
        rebotes: 4,
        faltasCometidas: 1,
      },
      jugador10: {
        puntos: 12,
        tirosLibres: { anotados: 2, fallados: 1 },
        tirosDos: { anotados: 3, fallados: 2 },
        tirosTres: { anotados: 1, fallados: 2 },
        asistencias: 2,
        rebotes: 3,
        faltasCometidas: 1,
      },
    },
  },
  estadisticasEquipos: {
    porCuarto: {
      Q1: {
        local: {
          puntos: 18,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 5, fallados: 2 },
          tirosTres: { anotados: 1, fallados: 2 },
          asistencias: 3,
          rebotes: 6,
          faltasCometidas: 2,
        },
        visitante: {
          puntos: 15,
          tirosLibres: { anotados: 2, fallados: 1 },
          tirosDos: { anotados: 4, fallados: 2 },
          tirosTres: { anotados: 1, fallados: 1 },
          asistencias: 2,
          rebotes: 5,
          faltasCometidas: 1,
        },
      },
      Q2: {
        local: {
          puntos: 15,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 4, fallados: 3 },
          tirosTres: { anotados: 1, fallados: 1 },
          asistencias: 2,
          rebotes: 5,
          faltasCometidas: 1,
        },
        visitante: {
          puntos: 16,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 5, fallados: 2 },
          tirosTres: { anotados: 1, fallados: 2 },
          asistencias: 3,
          rebotes: 5,
          faltasCometidas: 1,
        },
      },
      Q3: {
        local: {
          puntos: 20,
          tirosLibres: { anotados: 4, fallados: 1 },
          tirosDos: { anotados: 6, fallados: 2 },
          tirosTres: { anotados: 2, fallados: 1 },
          asistencias: 4,
          rebotes: 7,
          faltasCometidas: 2,
        },
        visitante: {
          puntos: 17,
          tirosLibres: { anotados: 4, fallados: 1 },
          tirosDos: { anotados: 5, fallados: 3 },
          tirosTres: { anotados: 1, fallados: 1 },
          asistencias: 3,
          rebotes: 5,
          faltasCometidas: 2,
        },
      },
      Q4: {
        local: {
          puntos: 18,
          tirosLibres: { anotados: 2, fallados: 0 },
          tirosDos: { anotados: 4, fallados: 3 },
          tirosTres: { anotados: 2, fallados: 2 },
          asistencias: 3,
          rebotes: 6,
          faltasCometidas: 2,
        },
        visitante: {
          puntos: 18,
          tirosLibres: { anotados: 3, fallados: 1 },
          tirosDos: { anotados: 4, fallados: 4 },
          tirosTres: { anotados: 2, fallados: 1 },
          asistencias: 2,
          rebotes: 4,
          faltasCometidas: 3,
        },
      },
    },
    totales: {
      local: {
        puntos: 71,
        tirosLibres: { anotados: 12, fallados: 3 },
        tirosDos: { anotados: 19, fallados: 10 },
        tirosTres: { anotados: 6, fallados: 6 },
        asistencias: 12,
        rebotes: 24,
        faltasCometidas: 7,
      },
      visitante: {
        puntos: 66,
        tirosLibres: { anotados: 12, fallados: 4 },
        tirosDos: { anotados: 18, fallados: 11 },
        tirosTres: { anotados: 5, fallados: 5 },
        asistencias: 10,
        rebotes: 19,
        faltasCometidas: 7,
      },
    },
  },
  jugadoresPresentes: {
    local: {
      jugador1: {
        nombre: 'Carlos',
        apellidos: 'Gómez Pérez',
        photoURL: 'https://example.com/foto1.png',
      },
      jugador2: {
        nombre: 'Luis',
        apellidos: 'Martínez Ruiz',
        photoURL: 'https://example.com/foto2.png',
      },
      jugador3: {
        nombre: 'Andrés',
        apellidos: 'López Díaz',
        photoURL: 'https://example.com/foto3.png',
      },
      jugador4: {
        nombre: 'Pedro',
        apellidos: 'Fernández Mora',
        photoURL: 'https://example.com/foto4.png',
      },
      jugador5: {
        nombre: 'Javier',
        apellidos: 'Sánchez León',
        photoURL: 'https://example.com/foto5.png',
      },
    },
    visitante: {
      jugador6: {
        nombre: 'Iván',
        apellidos: 'Ramírez Torres',
        photoURL: 'https://example.com/foto6.png',
      },
      jugador7: {
        nombre: 'Miguel',
        apellidos: 'Hernández Ruiz',
        photoURL: 'https://example.com/foto7.png',
      },
      jugador8: {
        nombre: 'David',
        apellidos: 'Ortega Méndez',
        photoURL: 'https://example.com/foto8.png',
      },
      jugador9: {
        nombre: 'Adrián',
        apellidos: 'García Romero',
        photoURL: 'https://example.com/foto9.png',
      },
      jugador10: {
        nombre: 'Sergio',
        apellidos: 'Castro Delgado',
        photoURL: 'https://example.com/foto10.png',
      },
    },
  },
};
